


CREATE TABLE IF NOT EXISTS `connxion` (
  `id` varchar(20) NOT NULL,
  `cpt` varchar(100) NULL,
  `IP` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `blog` (
  `user_name` varchar(20) NOT NULL,
  `titre` varchar(100) NULL,
  `texte` text NOT NULL,
  `phrase` varchar(200) NULL,
  `heure` timestamp default CURRENT_TIMESTAMP,
  `pseudo` varchar(50) NULL,
  `img` varchar(250) NULL,
  `vote` int(2) NULL,
  `retirer` varchar(1) NULL,
  `retireurIP` varchar(20) NULL,
  `IP` varchar(20) NULL,
  `code` varchar(50) NULL,
  PRIMARY KEY (`heure`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

--
-- Contenu de la table `articles`
--

INSERT INTO `blog` (`user_name`, `titre`, `texte`, `phrase`, `heure`, `pseudo`, `img`, `vote`, `retirer`, `retireurIP`, `IP`, `code`) VALUES
('octobre', 'teste', 'dskjmljkmldsfjkdfsljkfds', '', '2014-10-06 01:14:10', '', 'aaa', '0', '', '', '', '');



CREATE TABLE IF NOT EXISTS `articles` (
  `id_produits` int(11) NOT NULL AUTO_INCREMENT,
  `nom` varchar(100) NOT NULL,
  `user_name` varchar(100) NOT NULL,
  `auteur` varchar(100) NOT NULL,
  `img` varchar(150) NOT NULL,
  `fr` varchar(150) NOT NULL,
  `en` varchar(150) NOT NULL,
  `es` varchar(150) NOT NULL,
  `fr1` text NOT NULL,
  `en1` text NOT NULL,
  `es1` text NOT NULL,
  `taille` varchar(15) NOT NULL,
  `materiaux` varchar(20) NOT NULL,
  `autre` varchar(20) NOT NULL,
  `prix` int(6) NOT NULL,
  `stock` int(11) NOT NULL DEFAULT '1',
  `vendus` int(11) NOT NULL DEFAULT '0',
  `actif` tinyint(1) NOT NULL DEFAULT '1',
  `code` varchar(50) NOT NULL,
  PRIMARY KEY (`id_produits`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

--
-- Contenu de la table `articles`
--

INSERT INTO `articles` (`id_produits`, `nom`, `user_name`, `auteur`, `img`, `fr`, `en`, `es`, `fr1`, `en1`, `es1`, `taille`, `materiaux`, `autre`, `prix`, `stock`, `vendus`, `actif`, `code`) VALUES
(NULL, 'tableau/icone', 'objet', '', 'notre-dame-de-toutes-graces', 'Notre Dame de toutes Grâces', '', '', 'Nous avons 4 tailles différentes pour les icône religieuse.<br/>Veuillez faire le choix entre <ul><li>5cm/10cm</li><li>20cm/25cm</li><li>30cm/40cm</li><li>50cm/70cm</li></ul>dans le menu déroulant ci-avant:', '', '', '5cm/10cm', '', '', 1500, 15, 15, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'notre-dame-lourdes', 'Notre Dame de Lourdes', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'notre-dame-de-medjugorje', 'Notre Dame de Medjugorje', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'notre-dame-de-garabandal', 'Notre Dame de Guadeloupe', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'notre-dame-de-la-compassion', 'Notre Dame de la Compassion', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'notre-dame-de-la-guadeloupe', 'Notre Dame de la Guadeloupe', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 1, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'notre-dame-de-la-tendresse', 'Notre Dame de la Tendresse', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 3, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'notre-dame-de-la-tendresse-1', 'Notre Dame de la Tendresse', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'notre-dame-du-perpetuel-secours', 'Notre Dame du perpétuel secours', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'notre-dame-du-perpetuel-secours-dore', 'Notre Dame du perpétuel secours doré', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'la-vierge-et-enfant', "La Vierge et l'enfant", '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'la-vierge-noire-et-enfant', "La Vierge Noire et l'enfant", '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'notre-dame-fatima', 'Notre Dame de Fatima', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'notre-dame-du-bon-conseil', 'Notre Dame du bon conseil', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'coeur-sacre-de-jesus', 'Coeur Sacré de Jésus', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'coeur-sacre-de-jesus-1', 'Coeur Sacré de Jésus', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'coeur-sacre-de-jesus-2', 'Coeur Sacré de Jésus', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'jesus-en-meditation', 'Jésus en méditation', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'jesus-ressuscite', 'Jésus réssuscité', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'jesus-misericordieux', 'Jésus miséricordieux', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'visage-jesus-misericordieux', 'Visage de Jésus miséricordieux', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'jesus-crucifie', 'Jésus Crucifié', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'jesus-crucifie-1', 'Jésus Crucifié', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'jesus-crucifie-2', 'Jésus Crucifié', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'jesus-enseigne', 'Jésus enseigne', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'jesus-enseigne-1', 'Jésus enseigne', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'jesus-enseigne-2', 'Jésus enseigne', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'jesus-epine', 'Jésus épine', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'jesus-eucharistie', 'Jésus Eucharistie', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'sainte-face', 'La Sainte Face', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'saint-sacrement', 'Saint Sacrement', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'sainte-famille', 'La Sainte Famille', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'sainte-famille-1', 'La Sainte Famille', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'sainte-famille-2', 'La Sainte Famille', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'sainte-cene', 'La Sainte Cène', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'saint-michel-archange', 'Saint Michel Archange', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'saint-gabriel-archange', 'Ange de la musique', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'sainte-trinite', 'Sainte Trinité', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'saint-antoine', 'Saint Antoine', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'saint-esprit', 'Saint Esprit', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'saint-therese', 'Sainte Therèse', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'saint-francois-assise', "Saint François d'assise", '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'saint-joseph', 'Saint Joseph', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'la-pieta', 'La Pieta', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'padre-pio', 'Padré pio', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'padre-pio-1', 'Padré pio', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'coeur-immacule', 'Coeur Immaculé de Marie', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'coeur-immacule-1', 'Coeur Immaculé de Marie', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'croix-de-st-francois', 'Croix de Saint François', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'pape-francois', 'Pape François', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'tableau/icone', 'objet', '', 'pape-francois-1', 'Pape François', '', '', '', '', '', '5cm/10cm', '', '', 1500, 10, 0, 1, ''),
(NULL, 'livret P.D', 'publication', 'Maria Valtorta', 'evangile-revele-maria-valtorta-1', "<b>L'&Eacute;vangile Révélé</b> <i>Maria Valtorta</i><br/> Coffret 1: La préparation (3 livrets)<br/>", '', '', "&Eacute;vangile révélé à Maria valtirta) en 10 volumes de 6500 pages subdivisés en 55 livrets de 80 à 120 pages (gros caractères, facils et agréables à lire). C'est certainement l'une des plus grandes révélations privées de l'histoire de l'&Eacute;glise catholique par la densité, la puissance et la force de ses enseignements... Méditer régulièrement l'&Eacute;vangile Révélé est une grande bénédiction pour soi. Il faut plonger dans l'océan de l'amour et de la sagesse de Dieu.", '', '', '21cm/15cm', '', '80-120', 7500, 10, 0, 1, ''),
(NULL, 'livret P.D', 'publication', 'Maria Valtorta', 'evangile-revele-maria-valtorta-2', "<b>L'&Eacute;vangile Révélé</b> <i>Maria Valtorta</i><br/> Coffret 2: 1ère année de la vie publique de Jésus (8 livrets)<br/>", '', '', "&Eacute;vangile révélé à Maria valtirta) en 10 volumes de 6500 pages subdivisés en 55 livrets de 80 à 120 pages (gros caractères, facils et agréable à lire). C'est certainement l'une des plus grandes révélations privées de l'histoire de l'&Eacute;glise catholique par la densité, la puissance et la force de ses enseignements... Méditer régulièrement l'&Eacute;vangile Révélé est une grande bénédiction pour soi. Il faut plonger dans l'océan de l'amour et de la sagesse de Dieu.", '', '', '21cm/15cm', '', '80-120', 20000, 5, 0, 1, ''),
(NULL, 'livret P.D', 'publication', 'Maria Valtorta', 'evangile-revele-maria-valtorta-3', "<b>L'&Eacute;vangile Révélé</b> <i>Maria Valtorta</i><br/> Coffret 3: 2ème année de la vie publique de Jésus (14 livrets)<br/>", '', '', "&Eacute;vangile révélé à Maria valtirta) en 10 volumes de 6500 pages subdivisés en 55 livrets de 80 à 120 pages (gros caractères, facils et agréable à lire). C'est certainement l'une des plus grandes révélations privées de l'histoire de l'&Eacute;glise catholique par la densité, la puissance et la force de ses enseignements... Méditer régulièrement l'&Eacute;vangile Révélé est une grande bénédiction pour soi. Il faut plonger dans l'océan de l'amour et de la sagesse de Dieu.", '', '', '21cm/15cm', '', '80-120', 35000, 3, 0, 1, ''),
(NULL, 'livret P.D', 'publication', 'Maria Valtorta', 'evangile-revele-maria-valtorta-4', "<b>L'&Eacute;vangile Révélé</b> <i>Maria Valtorta</i><br/> Coffret 4: 3ème année de la vie publique de Jésus (1/2) (10 livrets)<br/>", '', '', "&Eacute;vangile révélé à Maria valtirta) en 10 volumes de 6500 pages subdivisés en 55 livrets de 80 à 120 pages (gros caractères, facils et agréable à lire). C'est certainement l'une des plus grandes révélations privées de l'histoire de l'&Eacute;glise catholique par la densité, la puissance et la force de ses enseignements... Méditer régulièrement l'&Eacute;vangile Révélé est une grande bénédiction pour soi. Il faut plonger dans l'océan de l'amour et de la sagesse de Dieu.", '', '', '21cm/15cm', '', '80-120', 25000, 3, 0, 1, ''),
(NULL, 'livret P.D', 'publication', 'Maria Valtorta', 'evangile-revele-maria-valtorta-4', "<b>L'&Eacute;vangile Révélé</b> <i>Maria Valtorta</i><br/> Coffret 5: 3ème année de la vie publique de Jésus (2/2) (8 livrets)<br/>", '', '', "&Eacute;vangile révélé à Maria valtirta) en 10 volumes de 6500 pages subdivisés en 55 livrets de 80 à 120 pages (gros caractères, facils et agréable à lire). C'est certainement l'une des plus grandes révélations privées de l'histoire de l'&Eacute;glise catholique par la densité, la puissance et la force de ses enseignements... Méditer régulièrement l'&Eacute;vangile Révélé est une grande bénédiction pour soi. Il faut plonger dans l'océan de l'amour et de la sagesse de Dieu.", '', '', '21cm/15cm', '', '80-120', 20000, 3, 0, 1, ''),
(NULL, 'livret P.D', 'publication', 'Maria Valtorta', 'evangile-revele-maria-valtorta-5', "<b>L'&Eacute;vangile Révélé</b> <i>Maria Valtorta</i><br/> Coffret 6: Pré-passion & Passion (9 livrets)<br/>", '', '', "&Eacute;vangile révélé à Maria valtirta) en 10 volumes de 6500 pages subdivisés en 55 livrets de 80 à 120 pages (gros caractères, facils et agréables à lire). C'est certainement l'une des plus grandes révélations privées de l'histoire de l'&Eacute;glise catholique par la densité, la puissance et la force de ses enseignements... Méditer régulièrement l'&Eacute;vangile Révélé est une grande bénédiction pour soi. Il faut plonger dans l'océan de l'amour et de la sagesse de Dieu.", '', '', '21cm/15cm', '', '80-120', 22500, 3, 0, 1, ''),
(NULL, 'livret P.D', 'publication', 'Maria Valtorta', 'evangile-revele-maria-valtorta-6', "<b>L'&Eacute;vangile Révélé</b> <i>Maria Valtorta</i><br/> Coffret 7: La Glorification (3 livrets)<br/>", '', '', "&Eacute;vangile révélé à Maria valtirta) en 10 volumes de 6500 pages subdivisés en 55 livrets de 80 à 120 pages (gros caractères, facils et agréables à lire). C'est certainement l'une des plus grandes révélations privées de l'histoire de l'&Eacute;glise catholique par la densité, la puissance et la force de ses enseignements... Méditer régulièrement l'&Eacute;vangile Révélé est une grande bénédiction pour soi. Il faut plonger dans l'océan de l'amour et de la sagesse de Dieu.", '', '', '21cm/15cm', '', '80-120', 7500, 3, 0, 1, ''),
(NULL, 'livret P.D', 'publication', 'Fraternité PDA', 'evangile-explique', "L'&Eacute;vangile expliqué: Collection 24 cahier", '', '', "24 cahiers d'énseignements thématique portant sur l'évangile de Jésus et extrait de l'Evangile Révélé (à Maria Valtorta). La méditation quotidienne de l'Evangile expliqué est un chemin de sanctification", '', '', '15cm/10cm', '', '60-300', 3000, 10, 0, 1, ''),
(NULL, 'livret P.D', 'publication', 'ACHI KOMAN', 'st-martin-de-porres', 'Neuvaine à Saint Martin de Porrès ou frère de la charte', '', '', "...à la découverte de l'un des plus grands saints de l'Eglise catholique. Il est invoqué pour les catholique. Il est invoqué pour les causes désespérées et les cas dits impossibles.", '', '', '21cm/15cm', '', '60', 2000, 10, 0, 1, ''),
(NULL, 'livret P.D', 'publication', 'ACHI KOMAN', 'priez', 'PRIEZ: <i>le matin, à 15H, le soir</i>', '', '', "Le matin avec l'Esprit-Saint pour se revêtir de sa puissance.<br/>À 15h, avec des prières d'intercession et de réparation pour soi-même, pour les autres et pour les âmes du purgatoire.<br/>Le soir, avec la prière du Rosaire du Coeur d'accueil de Jésus pour le combat contre les forces des ténèbres.", '', '', '15cm/10cm', '', '91', 1000, 10, 0, 1, ''),
(NULL, 'livret P.D', 'publication', 'ACHI KOMAN', 'priere-de-combat', 'Prière de combat', '', '', "Puissantes prières de délivrance, de libération et de protection contre toutes formes de maléfices", '', '', '15cm/10cm', '', '97', 1000, 10, 0, 1, ''),
(NULL, 'livret P.D', 'publication', 'ACHI KOMAN', 'priere-des-1000-ave', 'Prière des 1000 Ave', '', '', "Prières particulièrement efficaces pour les situations de blocage et la libération des âmes du purgatoire.", '', '', '15cm/10cm', '', '31', 1000, 10, 1, 1, ''),
(NULL, 'livret P.D', 'publication', 'ACHI KOMAN', 'neuvaine-esprit-saint', "Neuvaine à l'Esprit-Saint", '', '', "Pour recevoir l'Esprit-Saint, ses dons et ses charismes.", '', '', '15cm/10cm', '', '76', 800, 10, 0, 1, ''),
(NULL, 'livret P.D', 'publication', 'ACHI KOMAN', 'neuvaine-de-delivrance', 'Neuvaine de délivrance', '', '', "Pour briser les liens de la sorcellerie, vaincre et chasser les maris de nuit et femmes de nuit et obtenir la grâce du mariage.", '', '', '15cm/10cm', '', '56', 500, 10, 0, 1, ''),
(NULL, 'livret P.D', 'publication', 'ACHI KOMAN', 'le-purgatoire-existe', 'Le purgatoire existe', '', '', "Il y a des gens qui ne veulent pas accepter l'idée de l'existence d'un purgatoire et d'un enfer. Erreur!!!<br/>Le purgatoire existe, l'Enfer existe. Ce livre rapporte des témoignages poignants de leur existence.", '', '', '21cm/14.5cm', '', '69', 500, 10, 0, 1, ''),
(NULL, 'livret P.D', 'publication', 'ACHI KOMAN', 'parole-amour', "Paroles d'Amour", '', '', "Puissantes paroles du Seigneur Jésus-Christ pour enseigner la Paix, l'Amour, la Sagesse et la connaissance de Dieu, l'Obéïssance, la Bonté, la Miséricorde etc..", '', '', '15cm/10cm', '', '81', 1000, 10, 0, 1, ''),
(NULL, 'livret P.D', 'publication', 'ACHI KOMAN', 'apocalypse-13', 'Apocalypse 13', '', '', "Le chiffre de la bête: 666 énoncé dans l'Apocalypse de Saint Jean, au chapitre 13, est expliqué par la Sainte Vierge Marie qui donne par ailleurs les précautions de survie pour les évenements annoncés pour la fin des temps, mais pour aussi l'avènement du règne de Dieu, règne d'amour et de sainteté.", '', '', '21cm/15cm', '', '54', 1200, 10, 0, 1, ''),
(NULL, 'livret P.D', 'publication', 'ACHI KOMAN', 'chretien-rosicrucien', 'Peut-on être Chétiens et Rosicrusien', '', '', '', '', '', '21cm/15cm', '', '35', 500, 10, 0, 0, ''),
(NULL, 'bibles', 'publication', '', 'la-bible-des-peuples', 'La bible des peuples', '', '', 'à completer', '', '', '', '', '', 8000, 3, 0, 1, ''),
(NULL, 'bibles', 'publication', '', 'bible-bahoule', 'La bible en Bahoulé', '', '', 'à completer', '', '', '', '', '', 7000, 3, 0, 1, ''),
(NULL, 'bibles', 'publication', '', 'bible-communaute-chretienne', 'La bible des communautes chretiennes', '', '', 'à completer', '', '', '', '', '', 7000, 3, 0, 1, ''),
(NULL, 'bibles', 'publication', '', 'bible-de-jerusalem', 'La bible de Jérusalem', '', '', 'à completer', '', '', '', '', '', 10000, 3, 0, 1, ''),
(NULL, 'bibles', 'publication', '', 'bible-francais-courant', 'La bible en français courant', '', '', 'à completer', '', '', '', '', '', 5000, 0, 0, 1, ''),
(NULL, 'bibles', 'publication', '', 'cathechisme-eglise-catholique', "Compendium du cathechisme de l'église catholique", '', '', 'à completer', '', '', '', '', '', 4000, 3, 0, 1, ''),
(NULL, 'bibles', 'publication', '', 'bible-tob', 'La bible tob', '', '', 'à completer', '', '', '', '', '', 5000, 3, 0, 1, ''),
(NULL, 'bibles', 'publication', '', 'bible-enfant-ma-petitebible', 'Bible pour enfant: ma petite bible', '', '', 'à completer', '', '', '', '', '', 6500, 0, 0, 1, ''),
(NULL, 'bibles', 'publication', '', 'bible-enfant-ma-premeire-bible', 'Ma première bible', '', '', 'à completer', '', '', '', '', '', 3500, 3, 0, 1, ''),
(NULL, 'bibles', 'publication', '', 'bible-des-tout-petits', 'Bible des tout petits', '', '', 'à completer', '', '', '', '', '', 8000, 2, 0, 1, ''),
(NULL, 'bibles', 'publication', '', 'sainte-bible', 'La Sainte Bible Louïs Segond', '', '', 'à completer', '', '', '', '', '', 5000, 3, 0, 1, ''),
(NULL, 'bibles', 'publication', '', 'sainte-bible-louis-second', 'La Sainte Bible Louïs Segond (gros caractère avec dictionnaire des concordances)', '', '', 'à completer', '', '', '', '', '', 22000, 3, 0, 1, ''),
(NULL, 'NEI', 'publication', '', 'veillez-et-priez', 'Veillez et priez', '', '', 'à completer', '', '', '', '', '', 3500, 3, 0, 1, ''),
(NULL, 'texte&priere', 'publication', '', 'saint-raphael', 'Texte et Prière:<br/>Saint Raphaël', '', '', 'à completer', '', '', '', '', '71', 5000, 5, 0, 1, ''),
(NULL, 'texte&priere', 'publication', '', 'saint-gabriel', 'Texte et Prière:<br/>Saint Gabriel', '', '', 'à completer', '', '', '', '', '71', 5000, 5, 0, 1, ''),
(NULL, 'texte&priere', 'publication', '', 'saint-benoit', 'Texte et Prière:<br/>Saint Benoît', '', '', 'à completer', '', '', '', '', '59', 5000, 5, 0, 1, ''),
(NULL, 'texte&priere', 'publication', '', 'saint-ange-gardien', "Texte et Prière:<br/>L'ange gardien", '', '', 'à completer', '', '', '', '', '71', 5000, 5, 0, 1, ''),
(NULL, 'texte&priere', 'publication', '', 'saint-st-michel', "Texte et Prière:<br/>La dévotion à SAINT MICHEL et aux ANGES", '', '', 'à completer', '', '', '', '', '71', 5500, 5, 0, 1, ''),
(NULL, 'divers', 'objet', '', 'pierre-noire', 'Pierre noire', '', '', 'à completer', '', '', '', '', '', 1000, 10, 0, 1, ''),
(NULL, 'encens', 'objet', '', 'saint-jean-geranium', 'Saint Jean au <b>Geranium</b>', '', '', 'à completer', '', '', '', '', '', 2500, 10, 0, 0, ''),
(NULL, 'encens', 'objet', '', 'saint-expedito-jasmin', 'Encens Saint Expedito au <b>Jasmin</b>', '', '', 'à completer', '', '', '', '', '', 2500, 10, 0, 0, ''),
(NULL, 'encens', 'objet', '', 'sainte-therese-jesus-fleur-oranger', 'Sainte thérèse de Jésus à la <b>Fleur d''oranger</b>', '', '', 'à completer', '', '', '', '', '', 2500, 10, 0, 0, ''),
(NULL, 'encens', 'objet', '', 'saint-pedro-jacinthe', 'Saint Pédro à la <b>Jacinthe</b>', '', '', 'à completer', '', '', '', '', '', 2500, 10, 0, 0, ''),
(NULL, 'encens', 'objet', '', 'sainte-rita-mugue', 'Saint Rita au <b>Muguet</b>', '', '', 'à completer', '', '', '', '', '', 2500, 10, 0, 0, ''),
(NULL, 'encens', 'objet', '', 'saint-francois-assise-eucalyptus', 'Saint François d''Assise à <b>l''Eucalyptus</b>', '', '', 'à completer', '', '', '', '', '', 2500, 10, 0, 0, ''),
(NULL, 'encens', 'objet', '', 'marie-auxiliadora-jasmin', 'Maria Auxiliadora au <b>Jasmin</b>', '', '', 'à completer', '', '', '', '', '', 2500, 10, 0, 0, ''),
(NULL, 'encens', 'objet', '', 'saint-raphael-archange-myrrhe', 'Saint Raphaël archange à la <b>Myrrhe</b>', '', '', 'à completer', '', '', '', '', '', 2500, 10, 0, 1, ''),
(NULL, 'encens', 'objet', '', 'saint-michel-archange-encens-naturel', 'Saint Michel archange à <b>l''Encens Naturel</b>', '', '', 'à completer', '', '', '', '', '', 2500, 10, 0, 1, ''),
(NULL, 'encens', 'objet', '', 'saint-gabriel-archange-oeillet', 'Saint gabriel archange à <b>l''Oeillet</b>', '', '', 'à completer', '', '', '', '', '', 2500, 10, 0, 1, ''),
(NULL, 'encens', 'objet', '', 'ange-guerison-lavande', 'L''ange de la guérison à la <b>Lavande</b>', '', '', 'à completer', '', '', '', '', '', 2500, 10, 0, 0, ''),
(NULL, 'encens', 'objet', '', 'sainte-mere-lourdes-muguet', 'Sainte mère de Lourdes au <b>Muguet</b>', '', '', 'à completer', '', '', '', '', '', 2500, 10, 0, 1, ''),
(NULL, 'encens', 'objet', '', 'sainte-mere-du-perpetuel-secours-citron', 'Sainte mère du pertpétuel secours au <b>Citron</b>', '', '', 'à completer', '', '', '', '', '', 2500, 10, 0, 0, ''),
(NULL, 'encens', 'objet', '', 'sainte-mere-de-fatima-rose', 'Sainte mère de Fatima à la <b>Rose</b>', '', '', 'à completer', '', '', '', '', '', 2500, 10, 0, 0, ''),
(NULL, 'encens', 'objet', '', 'encens-jerusalem', 'Encens Jérusalem', '', '', 'à completer', '', '', '', '', '', 2500, 10, 0, 1, ''),
(NULL, 'encens', 'objet', '', 'encens-pontfical', 'Encens Pontifical', '', '', 'à completer', '', '', '', '', '', 2500, 10, 0, 1, ''),
(NULL, 'encens', 'objet', '', 'encens-st-michel', 'Encens Saint-Michel', '', '', 'à completer', '', '', '', '', '', 2500, 10, 0, 1, ''),
(NULL, 'croix', 'objet', '', 'crucifix-bois', 'Crucifix en bois', '', '', 'à completer', '', '', '', '', '', 600, 10, 0, 1, ''),
(NULL, 'croix', 'objet', '', 'crucifix-bois-posee', 'Crucifix en bois posée', '', '', 'à completer', '', '', '', '', '', 1000, 10, 0, 1, ''),
(NULL, 'croix', 'objet', '', 'crucifix-bronze', 'Crucifix en bronze', '', '', 'à completer', '', '', '42cm/21cm', '', '', 33000, 2, 0, 1, ''),
(NULL, 'croix', 'objet', '', 'croix-st-benoit', 'Croix mur de Saint Benoit', '', '', 'à completer', '', '', '', '', '', 3000, 10, 0, 1, ''),
(NULL, 'croix', 'objet', '', 'croix-posee-st-benoit', 'Croix posée de Saint Benoit', '', '', 'à completer', '', '', '', '', '', 3500, 10, 0, 1, ''),
(NULL, 'croix', 'objet', '', 'croix-posee-st-benoit-bleu', 'Croix posée de Saint Benoit', '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 0, ''),
(NULL, 'croix', 'objet', '', 'croix-st-esprit', "Croix du Saint-Esprit", '', '', 'à completer', '', '', '18cm/9cm', '', '', 15000, 10, 0, 1, ''),
(NULL, 'croix', 'objet', '', 'croix-eucharistie', "Croix de l'Eucharistie", '', '', 'à completer', '', '', '18cm/9cm', '', '', 15000, 10, 0, 1, ''),
(NULL, 'croix', 'objet', '', 'st-benoit-beige', 'Croix de Saint Benoit ', '', '', 'à completer', '', '', '', '', '', 3000, 10, 0, 0, ''),
(NULL, 'croix', 'objet', '', 'st-benoit-bois', 'Croix de Saint Benoit', '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 0, ''),
(NULL, 'chapelet', 'objet', '', 'chapelet-doree-1', 'Chapelet dorée (cou)', '', '', 'à completer', '', '', '', '', '', 7000, 10, 0, 1, ''),
(NULL, 'chapelet', 'objet', '', 'chapelet-doree-2', 'Chapelet dorée (cou)', '', '', 'à completer', '', '', '', '', '', 7000, 10, 0, 1, ''),
(NULL, 'chapelet', 'objet', '', 'chapelet-doree-3', 'Chapelet dorée (cou)', '', '', 'à completer', '', '', '', '', '', 8000, 10, 0, 1, ''),
(NULL, 'chapelet', 'objet', '', 'chapelet-gregoire', 'Chapelet du Pape Saint Grégoire', '', '', "Le chapelet du Pape St Grégoire a été révélé au St père pour la délivrance massive et assurée des âmes du purgatoire. Il consiste à dire 75 Pater et Ave pendant 7 jours d'affilé accompagnés de 7 aumônes par jour pendant 7 jours.<br/>Il se dit ainsi:<br/><ul><li>Sur le crucifix: <ul><li>le credo.</li></ul></li>	<li>1er grain:<ul><li>Père éternel, je t'offre le Corps et le Sang, l'Âme et la Divinité de ton Fils bien-aimé, notre Seigneur Jésus-Christ, en réparation de nos péchés et de ceux du monde entier</li></ul></li>	<li>Les deux grains blancs :<ul><li>Notre père, qui ête au cieux....</li><li>Je vous salut Marie,....</li></ul></li><li>Sur le grain rouge:<ul><li>Gloire au Père,....</li></ul></li></ul> et ainsi de suite jusqy=uà la fin du chapelet.<br/>&Agrave, dire pendant 7 jours.", '', '', '', '', '', 2000, 10, 0, 1, ''),
(NULL, 'chapelet', 'objet', '', 'chapelet-saint-esprit', 'Chapelet du Saint-Esprit', '', '', "Il consiste à dire :<br/>V: Viens Saint-Esprit,<br/>R: Rempli les coeurs de tes fidèles<br/>et allume en eux le feu de ton amour.<br/>Avec le chapelet rouge à 7 grains du Saint-Esprit,il se dit ainsi:<br/><ul><li>Sur le crucifix:<ul><li>Dieu, viens à mon aide.</li><li>Seigneur à notre secours.</li></ul></li>	<li>Sur le premier grain:<ul><li>Gloire au Père au fils et au saint-esprit....</li><li>Gloire adoration bénédiction et amour à toi....</li></ul></li>	<li>Sur les 7 grains suivants:<ul><li>Viens saint-esprit....</li></ul></li><li>Terminer par:<ul><li>Gloire au Père,....</li><li>Gloire, adoration, bénédiction,....</li></ul></li></ul>Ainsi de suite jusqu'à la fin du chapelet.", '', '', '', '', '', 1000, 10, 0, 1, ''),
(NULL, 'chapelet', 'objet', '', 'chapelet-sauveur', 'Chapelet du Saint Sauveur', '', '', "&Agrave, dire pour les situations de détresse et d'angoisse, d'attaque psychique et spirituelle, et pour les pays en guerre. <br/>Il comporte 33 grains. Il se dit ainsi:<br/><ul><li>Sur le crucifix:<ul><li>Dieu, viens à mon aide.</li><li>Seigneur à notre secours.</li></ul></li>	<li>Sur le gros grain:<ul><li>Gloire au Père....</li></ul></li>	<li>Petits grains (en continu):<ul><li>Il n'y a de puissance que ta puissance, Seigneur Jésus! <br/>Viens me sauver <b>ou</b> Viens sauver x (dire le nom de la personne pour qui l'on prie).</li></ul></li><li>&Agrave, la fin:<ul><li>Gloire au Père,....</li></ul></li></ul>", '', '', '', '', '', 2000, 10, 0, 1, ''),

(NULL, 'grotte', 'objet', '', 'grotte-religieuse-ciment-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', 'Grotte Notre Dame de toute Grâce en ciment<br/>(sur commande uniquement: 15j pour envoie)', '', '', "Nous avons un atelier d'artisans locaux pour la fabrication de grotte en ciment. Cette équipe, basé au <a href='index.php?menu=lieu-bolobi'>Sanctuaire Notre Dame du Rosaire de Bolobi</a> produit, à l'aide de fournitures d'autres artisans des alentours, des grottes dans les dimensions suivante :<br/><ul><li>1m/0.5m : 50.000Fcfa</li><li>1.5m/1m : 100.000Fcfa</li><li>2.5m/1.5m : 200.000Fcfa</li><li>2m/1m : 175.000Fcfa</li></ul>", '', '', '', '', '', 50000, 10, 0, 1, ''),
(NULL, 'grotte', 'objet', '', 'grotte-religieuse-argile-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', 'Grotte Notre Dame de toute Grâce en argile<br/>(sur commande uniquement: 15j pour envoie)', '', '', "Nous avons un atelier d'artisans locaux pour la fabrication de grotte en argile. Cette équipe, basé au <a href='index.php?menu=lieu-bolobi'>Sanctuaire Notre Dame du Rosaire de Bolobi</a> produit, à l'aide de fournitures d'autres artisans des alentours, des grottes dans les dimensions suivante :<br/><ul><li>1m/0.5m : 30.000Fcfa</li><li>1.5m/1m : 70.000Fcfa</li><li>2.5m/1.5m : 150.000Fcfa</li><li>2m/1m : 125.000Fcfa</li></ul>", '', '', '', '', '', 50000, 10, 0, 1, ''),
(NULL, 'grotte', 'objet', '', 'grotte-religieuse-granite-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', 'Grotte Notre Dame de toute Grâce en granite<br/>(sur commande uniquement: 15j pour envoie)', '', '', "Nous avons un atelier d'artisans locaux pour la fabrication de grotte en granite.. Cette équipe, basé au <a href='index.php?menu=lieu-bolobi'>Sanctuaire Notre Dame du Rosaire de Bolobi</a> produit, à l'aide de fournitures d'autres artisans des alentours, des grottes dans les dimensions suivante :<br/><ul><li>1m/0.5m : 0.000Fcfa</li><li>1.5m/1m : 00.000Fcfa</li><li>2.5m/1.5m : 00.000Fcfa</li><li>2m/1m : 00.000Fcfa</li></ul>", '', '', '', '', '', 50000, 10, 0, 1, ''),

(NULL, 'statue', 'objet', '', 'statue-religieuse-platre-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', 'Statue Notre Dame de toute Grâce<br/>en platre<br/>(sur commande uniquement: 15j pour envoie)', '', '', "Nous avons un atelier d'artisans locaux pour la fabrication de statues en plâtre. Cette équipe, basé au <a href='index.php?menu=lieu-bolobi'>Sanctuaire Notre Dame du Rosaire de Bolobi</a> produit, à l'aide de fournitures d'autres artisans des alentours, des statues dans les dimensions suivante :<br/><ul><li>1m/0.5m : 0.000Fcfa</li><li>1.5m/1m : 00.000Fcfa</li><li>2.5m/1.5m : 00.000Fcfa</li><li>2m/1m : 00.000Fcfa</li></ul>", '', '', '', '', '', 50000, 10, 0, 1, ''),
(NULL, 'statue', 'objet', '', 'statue-religieuse-polyestere-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', 'Statue Notre Dame de toute Grâce<br/>en polyestère<br/>(sur commande uniquement: 15j pour envoie)', '', '', "Nous avons un atelier d'artisans locaux pour la fabrication de statues en polyestère. Cette équipe, basé au <a href='index.php?menu=lieu-bolobi'>Sanctuaire Notre Dame du Rosaire de Bolobi</a> produit, à l'aide de fournitures d'autres artisans des alentours, des statues dans les dimensions suivante :<br/><ul><li>1m/0.5m : 0.000Fcfa</li><li>1.5m/1m : 00.000Fcfa</li><li>2.5m/1.5m : 00.000Fcfa</li><li>2m/1m : 00.000Fcfa</li></ul>", '', '', '', '', '', 50000, 10, 0, 1, ''),
(NULL, 'statue', 'objet', '', 'statue-religieuse-ciment-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', 'Statue Notre Dame de toute Grâce<br/>en poudre de marbre<br/>(sur commande uniquement: 15j pour envoie)', '', '', "Nous avons un atelier d'artisans locaux pour la fabrication de statues en poudre de marbre. Cette équipe, basé au <a href='index.php?menu=lieu-bolobi'>Sanctuaire Notre Dame du Rosaire de Bolobi</a> produit, à l'aide de fournitures d'autres artisans des alentours, des statues dans les dimensions suivante :<br/><ul><li>1m/0.5m : 0.000Fcfa</li><li>1.5m/1m : 00.000Fcfa</li><li>2.5m/1.5m : 00.000Fcfa</li><li>2m/1m : 00.000Fcfa</li></ul>", '', '', '', '', '', 50000, 10, 0, 1, ''),
(NULL, 'statue', 'objet', '', 'statue-religieuse-marbre-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', 'Statue Notre Dame de toute Grâce<br/>en poudre de marbre<br/>(sur commande uniquement: 15j pour envoie)', '', '', "Nous avons un atelier d'artisans locaux pour la fabrication de statues en poudre de marbre. Cette équipe, basé au <a href='index.php?menu=lieu-bolobi'>Sanctuaire Notre Dame du Rosaire de Bolobi</a> produit, à l'aide de fournitures d'autres artisans des alentours, des statues dans les dimensions suivante :<br/><ul><li>1m/0.5m : 0.000Fcfa</li><li>1.5m/1m : 00.000Fcfa</li><li>2.5m/1.5m : 00.000Fcfa</li><li>2m/1m : 00.000Fcfa</li></ul>", '', '', '', '', '', 50000, 10, 0, 1, ''),
(NULL, 'statue', 'objet', '', 'statue-religieuse-granite-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', 'Statue Notre Dame de toute Grâce<br/>en granite<br/>(sur commande uniquement: 15j pour envoie)', '', '', "Nous avons un atelier d'artisans locaux pour la fabrication de statues en pourdre de granite. Cette équipe, basé au <a href='index.php?menu=lieu-bolobi'>Sanctuaire Notre Dame du Rosaire de Bolobi</a> produit, à l'aide de fournitures d'autres artisans des alentours, des statues dans les dimensions suivante :<br/><ul><li>1m/0.5m : 0.000Fcfa</li><li>1.5m/1m : 00.000Fcfa</li><li>2.5m/1.5m : 00.000Fcfa</li><li>2m/1m : 00.000Fcfa</li></ul>", '', '', '', '', '', 50000, 10, 0, 1, ''),

(NULL, 'statue', 'objet', '', 'statue-religieuse-resine-colore-sainte-vierge-marie-notre-dame-toute-grace', 'Statue Notre Dame de toute Grâce<br/>en résine : coloré', '', '', "Ces statues du Nigéria sont en résine. Leur déclinaison en taille varie comme suivant :<br/><ul><li>1m/0.5m : 0.000Fcfa</li><li>1.5m/1m : 00.000Fcfa</li><li>2.5m/1.5m : 00.000Fcfa</li><li>2m/1m : 00.000Fcfa</li></ul>", '', '', '', '', '', 50000, 10, 0, 1, ''),
(NULL, 'statue', 'objet', '', 'statue-religieuse-resine-lumineuse-sainte-vierge-marie-notre-dame-toute-grace', 'Statue Notre Dame de toute Grâce<br/>en résine : lumineuse', '', '', "Ces statues du Nigéria sont en résine. Leur déclinaison en taille varie comme suivant :<br/><ul><li>1m/0.5m : 0.000Fcfa</li><li>1.5m/1m : 00.000Fcfa</li><li>2.5m/1.5m : 00.000Fcfa</li><li>2m/1m : 00.000Fcfa</li></ul>", '', '', '', '', '', 50000, 10, 0, 1, ''),
(NULL, 'statue', 'objet', '', 'statue-religieuse-resine-lumineuse-jesus-misericordieux', 'Jésus miséricordieux<br/>en résine : coloré', '', '', "Ces statues du Nigéria sont en résine. Leur déclinaison en taille varie comme suivant :<br/><ul><li>1m/0.5m : 0.000Fcfa</li><li>1.5m/1m : 00.000Fcfa</li><li>2.5m/1.5m : 00.000Fcfa</li><li>2m/1m : 00.000Fcfa</li></ul>", '', '', '', '', '', 50000, 10, 0, 1, ''),
(NULL, 'statue', 'objet', '', 'statue-religieuse-resine-lumineuse-jesus-misericordieux', 'Statue Jésus miséricordieux<br/>en résine : lumineuse', '', '', "Ces statues du Nigéria sont en résine. Leur déclinaison en taille varie comme suivant :<br/><ul><li>1m/0.5m : 0.000Fcfa</li><li>1.5m/1m : 00.000Fcfa</li><li>2.5m/1.5m : 00.000Fcfa</li><li>2m/1m : 00.000Fcfa</li></ul>", '', '', '', '', '', 50000, 10, 0, 1, '');
















CREATE TABLE IF NOT EXISTS `options_article` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `img_article` varchar(150) NOT NULL,
  `stock` varchar(6) NOT NULL DEFAULT '1',
  `vendus` int(5) NOT NULL DEFAULT '0',
  `coloris` varchar(20) DEFAULT NULL,
  `couverture` int(4) DEFAULT NULL,
  `taille_` varchar(50) DEFAULT NULL,
  `opt_nom` varchar(50) DEFAULT NULL,
  `opt_prix` int(5) DEFAULT NULL,
  `autre` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=0 ;

--
-- Contenu de la table `options_article`
--

INSERT INTO `options_article` (`id`, `img_article`, `stock`, `vendus`, `coloris`, `couverture`, `taille_`, `opt_nom`, `opt_prix`, `autre`) VALUES
(NULL, 'croix-posee-st-benoit', '2', '0', NULL, NULL, '8cm/4cm', NULL, '3500', ""),
(NULL, 'croix-posee-st-benoit', '2', '0', NULL, NULL, '12cm/5cm', NULL, '7000', ""),
(NULL, 'croix-posee-st-benoit', '2', '0', NULL, NULL, '20cm/9.5cm', NULL, '20000', ""),
(NULL, 'croix-st-benoit', '2', '0', NULL, NULL, '8cm/4cm', NULL, '3000', ""),
(NULL, 'croix-st-benoit', '2', '0', NULL, NULL, '12cm/5cm', NULL, '4500', ""),
(NULL, 'croix-st-benoit', '2', '0', NULL, NULL, '20cm/9.5cm', NULL, '20000', ""),
(NULL, 'croix-st-benoit', '2', '0', NULL, NULL, '29cm/15cm', NULL, '30000', ""),
(NULL, 'croix-posee-st-benoit-bleu', '2', '0', 'bleu', NULL, NULL, NULL, NULL, ""),
(NULL, 'croix-posee-st-benoit-bleu', '2', '0', 'rouge', NULL, NULL, NULL, NULL, NULL),
(NULL, 'st-benoit-beige', '2', '0', 'beige', NULL, NULL, NULL, NULL,""),
(NULL, 'st-benoit-beige', '2', '0', 'doree', NULL, NULL, NULL, NULL,""),
(NULL, 'st-benoit-beige', '2', '0', 'noire', NULL, NULL, NULL, NULL,""),
(NULL, 'st-benoit-petit-beige', '2', '0', 'beige', NULL, NULL, NULL, NULL,""),
(NULL, 'st-benoit-petit-beige', '2', '0', 'bleu', NULL, NULL, NULL, NULL, ""),
(NULL, 'st-benoit-petit-beige', '2', '0', 'verte', NULL, NULL, NULL, NULL, ""),
(NULL, 'st-benoit-petit-beige', '2', '0', 'doree', NULL, NULL, NULL, NULL, ""),
(NULL, 'notre-dame-de-toutes-graces', '0', '0', NULL, NULL, '5cm/10cm', NULL, '1500', ""),
(NULL, 'notre-dame-de-toutes-graces', '2', '0', NULL, NULL, '20cm/25cm', NULL, '4500', ""),
(NULL, 'notre-dame-de-toutes-graces', '2', '0', NULL, NULL, '30cm/40cm', NULL, '12000', ""),
(NULL, 'notre-dame-de-toutes-graces', '2', '0', NULL, NULL, '50cm/70cm', NULL, '20000', ""),
-- (NULL, 'notre-dame-lourdes', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'notre-dame-lourdes', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
-- (NULL, 'notre-dame-lourdes', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
-- (NULL, 'notre-dame-lourdes', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
(NULL, 'notre-dame-de-medjugorje', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'notre-dame-de-medjugorje', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'notre-dame-de-medjugorje', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'notre-dame-de-medjugorje', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
-- (NULL, 'notre-dame-de-garabandal', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'notre-dame-de-garabandal', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
-- (NULL, 'notre-dame-de-garabandal', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
-- (NULL, 'notre-dame-de-garabandal', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
-- (NULL, 'notre-dame-de-la-compassion', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'notre-dame-de-la-compassion', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
-- (NULL, 'notre-dame-de-la-compassion', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'notre-dame-de-la-compassion', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
(NULL, 'notre-dame-de-la-guadeloupe', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
-- (NULL, 'notre-dame-de-la-guadeloupe', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'notre-dame-de-la-guadeloupe', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'notre-dame-de-la-guadeloupe', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
(NULL, 'notre-dame-de-la-tendresse', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
-- (NULL, 'notre-dame-de-la-tendresse', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
-- (NULL, 'notre-dame-de-la-tendresse', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'notre-dame-de-la-tendresse', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
(NULL, 'notre-dame-de-la-tendresse-1', '0', '0', NULL, NULL, '5cm/10cm', NULL, '2000', ""),
-- (NULL, 'notre-dame-de-la-tendresse-1', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
-- (NULL, 'notre-dame-de-la-tendresse-1', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'notre-dame-de-la-tendresse-1', '2', '0', NULL, NULL, '50cm/70cm', NULL, '23000', ""),
(NULL, 'notre-dame-du-perpetuel-secours', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'notre-dame-du-perpetuel-secours', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'notre-dame-du-perpetuel-secours', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'notre-dame-du-perpetuel-secours', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
-- (NULL, 'notre-dame-du-perpetuel-secours-dore', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
-- (NULL, 'notre-dame-du-perpetuel-secours-dore', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
-- (NULL, 'notre-dame-du-perpetuel-secours-dore', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'notre-dame-du-perpetuel-secours-dore', '2', '0', NULL, NULL, '50cm/70cm', NULL, '23000', ""),
-- (NULL, 'la-vierge-et-enfant', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
-- (NULL, 'la-vierge-et-enfant', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'la-vierge-et-enfant', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
-- (NULL, 'la-vierge-et-enfant', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
-- (NULL, 'la-vierge-noire-et-enfant', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
-- (NULL, 'la-vierge-noire-et-enfant', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'la-vierge-noire-et-enfant', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'la-vierge-noire-et-enfant', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
-- (NULL, 'notre-dame-fatima', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'notre-dame-fatima', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
-- (NULL, 'notre-dame-fatima', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
-- (NULL, 'notre-dame-fatima', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
-- (NULL, 'notre-dame-du-bon-conseil', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'notre-dame-du-bon-conseil', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'notre-dame-du-bon-conseil', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
-- (NULL, 'notre-dame-du-bon-conseil', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
(NULL, 'coeur-sacre-de-jesus', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'coeur-sacre-de-jesus', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'coeur-sacre-de-jesus', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'coeur-sacre-de-jesus', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
(NULL, 'coeur-sacre-de-jesus-1', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
-- (NULL, 'coeur-sacre-de-jesus-1', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'coeur-sacre-de-jesus-1', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'coeur-sacre-de-jesus-1', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
(NULL, 'coeur-sacre-de-jesus-2', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'coeur-sacre-de-jesus-2', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'coeur-sacre-de-jesus-2', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'coeur-sacre-de-jesus-2', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
(NULL, 'jesus-en-meditation', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'jesus-en-meditation', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'jesus-en-meditation', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'jesus-en-meditation', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
-- (NULL, 'jesus-ressuscite', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
-- (NULL, 'jesus-ressuscite', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
-- (NULL, 'jesus-ressuscite', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'jesus-ressuscite', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
(NULL, 'jesus-misericordieux', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'jesus-misericordieux', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'jesus-misericordieux', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'jesus-misericordieux', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
(NULL, 'visage-jesus-misericordieux', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'visage-jesus-misericordieux', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'visage-jesus-misericordieux', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'visage-jesus-misericordieux', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
-- (NULL, 'jesus-crucifie', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'jesus-crucifie', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
-- (NULL, 'jesus-crucifie', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'jesus-crucifie', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
-- (NULL, 'jesus-crucifie-1', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'jesus-crucifie-1', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
-- (NULL, 'jesus-crucifie-1', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
-- (NULL, 'jesus-crucifie-1', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
-- (NULL, 'jesus-crucifie-2', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
-- (NULL, 'jesus-crucifie-2', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
-- (NULL, 'jesus-crucifie-2', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'jesus-crucifie-2', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
-- (NULL, 'jesus-enseigne', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'jesus-enseigne', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
-- (NULL, 'jesus-enseigne', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
-- (NULL, 'jesus-enseigne', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
-- (NULL, 'jesus-enseigne-1', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
-- (NULL, 'jesus-enseigne-1', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'jesus-enseigne-1', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
-- (NULL, 'jesus-enseigne-1', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
-- (NULL, 'jesus-enseigne-2', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
-- (NULL, 'jesus-enseigne-2', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
-- (NULL, 'jesus-enseigne-2', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'jesus-enseigne-2', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
-- (NULL, 'jesus-epine', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'jesus-epine', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'jesus-epine', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'jesus-epine', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
-- (NULL, 'jesus-eucharistie', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
-- (NULL, 'jesus-eucharistie', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'jesus-eucharistie', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
-- (NULL, 'jesus-eucharistie', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
(NULL, 'sainte-face', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'sainte-face', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'sainte-face', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'sainte-face', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
(NULL, 'saint-sacrement', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'saint-sacrement', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'saint-sacrement', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'saint-sacrement', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
(NULL, 'sainte-famille', '2', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'sainte-famille', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
-- (NULL, 'sainte-famille', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
-- (NULL, 'sainte-famille', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
-- (NULL, 'sainte-famille-1', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
-- (NULL, 'sainte-famille-1', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'sainte-famille-1', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
-- (NULL, 'sainte-famille-1', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
-- (NULL, 'sainte-famille-2', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'sainte-famille-2', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
-- (NULL, 'sainte-famille-2', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
-- (NULL, 'sainte-famille-2', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
-- (NULL, 'sainte-cene', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'sainte-cene', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'sainte-cene', '0', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'sainte-cene', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
(NULL, 'saint-michel-archange', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'saint-michel-archange', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'saint-michel-archange', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'saint-michel-archange', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
-- (NULL, 'saint-gabriel-archange', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'saint-gabriel-archange', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
-- (NULL, 'saint-gabriel-archange', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
-- (NULL, 'saint-gabriel-archange', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
(NULL, 'sainte-trinite', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'sainte-trinite', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'sainte-trinite', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'sainte-trinite', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
(NULL, 'saint-antoine', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'saint-antoine', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
-- (NULL, 'saint-antoine', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
-- (NULL, 'saint-antoine', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
(NULL, 'saint-esprit', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'saint-esprit', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
-- (NULL, 'saint-esprit', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
-- (NULL, 'saint-esprit', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
(NULL, 'saint-therese', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'saint-therese', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
-- (NULL, 'saint-therese', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
-- (NULL, 'saint-therese', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
-- (NULL, 'saint-francois-assise', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'saint-francois-assise', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
-- (NULL, 'saint-francois-assise', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
-- (NULL, 'saint-francois-assise', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
(NULL, 'saint-joseph', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'saint-joseph', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'saint-joseph', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'saint-joseph', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
-- (NULL, 'la-pieta', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
-- (NULL, 'la-pieta', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'la-pieta', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'la-pieta', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
-- (NULL, 'padre-pio', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'padre-pio', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'padre-pio', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'padre-pio', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
-- (NULL, 'padre-pio-1', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'padre-pio-1', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
-- (NULL, 'padre-pio-1', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
-- (NULL, 'padre-pio-1', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
(NULL, 'coeur-immacule', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'coeur-immacule', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'coeur-immacule', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
(NULL, 'coeur-immacule', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
-- (NULL, 'coeur-immacule-1', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'coeur-immacule-1', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'coeur-immacule-1', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
-- (NULL, 'coeur-immacule-1', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
-- (NULL, 'croix-de-st-francois', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'croix-de-st-francois', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
(NULL, 'croix-de-st-francois', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
-- (NULL, 'croix-de-st-francois', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
-- (NULL, 'pape-francois', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
(NULL, 'pape-francois', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
-- (NULL, 'pape-francois', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
-- (NULL, 'pape-francois', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
(NULL, 'pape-francois-1', '0', '0', NULL, NULL, '5cm/10cm', NULL, NULL, ""),
-- (NULL, 'pape-francois-1', '2', '0', NULL, NULL, '20cm/25cm', NULL, NULL, ""),
-- (NULL, 'pape-francois-1', '2', '0', NULL, NULL, '30cm/40cm', NULL, NULL, ""),
-- (NULL, 'pape-francois-1', '2', '0', NULL, NULL, '50cm/70cm', NULL, NULL, ""),
(NULL, 'la-bible-des-peuples', '3', '0', NULL, "2500", NULL, NULL, NULL, ""),
(NULL, 'bible-bahoule', '3', '0', NULL, "2500", NULL, NULL, NULL, ""),
(NULL, 'bible-communaute-chretienne', '3', '0', NULL, "2000", NULL, NULL, NULL, ""),
(NULL, 'bible-de-jerusalem', '3', '0', NULL, "2500", NULL, NULL, NULL, ""),
(NULL, 'bible-francais-courant', '3', '0', NULL, "2000", NULL, NULL, NULL, ""),
-- (NULL, 'cathechisme-eglise-catholique', '3', '0', NULL, NULL, NULL, NULL, NULL, ""),
(NULL, 'bible-tob', '3', '0', NULL, "2000", NULL, NULL, NULL, ""),
-- (NULL, 'bible-des-tout-petits', '3', '0', NULL, "1500", NULL, NULL, NULL, ""),
-- (NULL, 'bible-enfant-ma-petitebible', '3', '0', NULL, "1500", NULL, NULL, NULL, ""),
-- (NULL, 'bible-enfant-ma-premeire-bible', '3', '0', NULL, "1500", NULL, NULL, NULL, ""),
(NULL, 'sainte-bible', '3', '0', NULL, "1000", NULL, NULL, NULL, ""),
-- (NULL, 'sainte-bible-louis-second', '3', '0', NULL, "1000", NULL, NULL, NULL, ""),
(NULL, 'veillez-et-priez', '3', '0', NULL, "1000", NULL, NULL, NULL, ""),
(NULL, 'evangile-explique', '5', '0', NULL, NULL, NULL,"La vie cachée de Jésus",'1500', '1'),
(NULL, 'evangile-explique', '5', '0', NULL, NULL, NULL,"Marie, la nouvelle Eve", NULL, '2'),
(NULL, 'evangile-explique', '5', '0', NULL, NULL, NULL,"Saint Joseph, vie et mort",'2000', '3'),
(NULL, 'evangile-explique', '5', '0', NULL, NULL, NULL,"La Tentation de Jésus au désert",'1500', '4'),
(NULL, 'evangile-explique', '5', '0', NULL, NULL, NULL,"L’élection des apôtres", NULL, '5'),
(NULL, 'evangile-explique', '5', '0', NULL, NULL, NULL,"Les 10 Commandements", NULL, '6'),
(NULL, 'evangile-explique', '5', '0', NULL, NULL, NULL,"Foi, Espérance, Charité", NULL, '7'),
(NULL, 'evangile-explique', '5', '0', NULL, NULL, NULL,"Le banquet de l’amour",'1000', '8'),
(NULL, 'evangile-explique', '5', '0', NULL, NULL, NULL,"Les béatitudes",'2500', '9'),
(NULL, 'evangile-explique', '5', '0', NULL, NULL, NULL,"Prendre soin des orphelins : un devoir chrétien",'1500', '10'),
(NULL, 'evangile-explique', '5', '0', NULL, NULL, NULL,"Satan",'1500', '11'),
(NULL, 'evangile-explique', '5', '0', NULL, NULL, NULL,"Judas, fils de Satan",'1500', '12'),
(NULL, 'evangile-explique', '5', '0', NULL, NULL, NULL,"Marie Madeleine",'2000', '13'),
(NULL, 'evangile-explique', '5', '0', NULL, NULL, NULL,"Judas, fils de Satan", NULL, '14'),
(NULL, 'evangile-explique', '5', '0', NULL, NULL, NULL,"La Passion du Christ",'2000', '15'),
(NULL, 'evangile-explique', '5', '0', NULL, NULL, NULL,"Crucifixion et mort du Christ",'1500', '16'),
(NULL, 'evangile-explique', '5', '0', NULL, NULL, NULL,"La Résurrection du Christ",'2500', '17'),
(NULL, 'evangile-explique', '5', '0', NULL, NULL, NULL,"Assomption de Marie",'1500', '18'),
(NULL, 'evangile-explique', '5', '0', NULL, NULL, NULL,"Les 7 Sacrements de l’Eglise apostolique",'2000', '19'),
(NULL, 'evangile-explique', '5', '0', NULL, NULL, NULL,"La Pentecôte",'1500', '20'),
(NULL, 'evangile-explique', '5', '0', NULL, NULL, NULL,"Prédications diverses au Temple de Jérusalem", NULL, '21'),
(NULL, 'evangile-explique', '5', '0', NULL, NULL, NULL,"Guérisons, miracles et prodiges",'2000', '22'),
(NULL, 'evangile-explique', '5', '0', NULL, NULL, NULL,"Guérisons, miracles et prodiges", NULL, '23'),
(NULL, 'evangile-explique', '5', '0', NULL, NULL, NULL,"Guérisons, miracles et prodiges", NULL, '24'),
(NULL, 'crucifix-bois', '10', '0', NULL, NULL, '11cm/5.5cm', NULL, '600', ""),
(NULL, 'crucifix-bois', '10', '0', NULL, NULL, '17cm/8cm', NULL, '1200', ""),
(NULL, 'crucifix-bois', '10', '0', NULL, NULL, '25cm/13cm', NULL, '2000', ""),
(NULL, 'crucifix-bois', '10', '0', NULL, NULL, '30cm/15cm', NULL, '2500', ""),
(NULL, 'crucifix-bois-posee', '10', '0', NULL, NULL, '11cm/5.5cm', NULL, '1000', ""),
(NULL, 'crucifix-bois-posee', '10', '0', NULL, NULL, '18cm/8cm', NULL, '1500', ""),
(NULL, 'crucifix-bois-posee', '10', '0', NULL, NULL, '27cm/13cm', NULL, '2500', ""),
(NULL, 'crucifix-bois-posee', '10', '0', NULL, NULL, '32cm/15cm', NULL, '3500', ""),
-- (NULL, 'crucifix-bois-posee', '10', '0', NULL, NULL, '12cm/5cm', NULL, '7000', ""),
-- (NULL, 'crucifix-bois-posee', '10', '0', NULL, NULL, '22cm/9.5cm', NULL, '20000', "");
(NULL, 'grotte-religieuse-ciment-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '1m/0.5cm', NULL, '50000', ""),
(NULL, 'grotte-religieuse-ciment-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '1.5m/1cm', NULL, '100000', ""),
(NULL, 'grotte-religieuse-ciment-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '2.5m/1.5cm', NULL, '200000', ""),
(NULL, 'grotte-religieuse-ciment-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '2m/1cm', NULL, '175000', ""),
(NULL, 'grotte-religieuse-argile-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '1m/0.5cm', NULL, '30000', ""),
(NULL, 'grotte-religieuse-argile-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '1.5m/1cm', NULL, '70000', ""),
(NULL, 'grotte-religieuse-argile-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '2.5m/1.5cm', NULL, '150000', ""),
(NULL, 'grotte-religieuse-argile-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '2m/1cm', NULL, '125000', ""),
(NULL, 'grotte-religieuse-granite-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '1m/0.5cm', NULL, '0000', ""),
(NULL, 'grotte-religieuse-granite-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '1.5m/1cm', NULL, '00000', ""),
(NULL, 'grotte-religieuse-granite-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '2.5m/1.5cm', NULL, '00000', ""),
(NULL, 'grotte-religieuse-granite-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '2m/1cm', NULL, '00000', ""),
(NULL, 'statue-religieuse-platre-doree-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '105cm', NULL, '80000', ""),
(NULL, 'statue-religieuse-platre-doree-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '90cm', NULL, '50000', ""),
(NULL, 'statue-religieuse-platre-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '105cm', NULL, '80000', ""),
(NULL, 'statue-religieuse-platre-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '90cm', NULL, '50000', ""),
(NULL, 'statue-religieuse-platre-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '123cm', NULL, '100000', ""),
(NULL, 'statue-religieuse-platre-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '77cm', NULL, '30000', ""),
(NULL, 'statue-religieuse-platre-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '63cm', NULL, '25000', ""),
(NULL, 'statue-religieuse-platre-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '45cm', NULL, '10000', ""),
(NULL, 'statue-religieuse-ciment-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '105cm', NULL, '110000', ""),
(NULL, 'statue-religieuse-ciment-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '63cm', NULL, '30000', ""),
(NULL, 'statue-religieuse-ciment-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '123cm', NULL, '120000', ""),
(NULL, 'statue-religieuse-polyestere-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '63cm', NULL, '25000', ""),
(NULL, 'statue-religieuse-polyestere-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '77cm', NULL, '35000', ""),
(NULL, 'statue-religieuse-marbre-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '1m/0.5cm', NULL, '0000', ""),
(NULL, 'statue-religieuse-marbre-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '1.5m/1cm', NULL, '00000', ""),
(NULL, 'statue-religieuse-marbre-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '2.5m/1.5cm', NULL, '00000', ""),
(NULL, 'statue-religieuse-marbre-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '2m/1cm', NULL, '00000', ""),
-- (NULL, 'statue-religieuse-granite-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '1m/0.5cm', NULL, '0000', ""),
-- (NULL, 'statue-religieuse-granite-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '1.5m/1cm', NULL, '00000', ""),
-- (NULL, 'statue-religieuse-granite-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '2.5m/1.5cm', NULL, '00000', ""),
-- (NULL, 'statue-religieuse-granite-sainte-vierge-marie-notre-dame-toute-grace-sur-commande', '2', '0', NULL, NULL, '2m/1cm', NULL, '00000', ""),
(NULL, 'statue-religieuse-resine-colore-sainte-vierge-marie-notre-dame-toute-grace', '2', '0', NULL, NULL, '35cm', NULL, '15000', ""),
(NULL, 'statue-religieuse-resine-colore-sainte-vierge-marie-notre-dame-toute-grace', '2', '0', NULL, NULL, '25cm', NULL, '10000', ""),
(NULL, 'statue-religieuse-resine-colore-sainte-vierge-marie-notre-dame-toute-grace', '2', '0', NULL, NULL, '16cm', NULL, '3000', ""),
(NULL, 'statue-religieuse-resine-colore-sainte-vierge-marie-notre-dame-toute-grace', '2', '0', NULL, NULL, '10cm', NULL, '2000', ""),
(NULL, 'statue-religieuse-resine-colore-jesus-misericordieux', '2', '0', NULL, NULL, '10cm/4cm', NULL, '1000', ""),
(NULL, 'statue-religieuse-resine-colore-jesus-misericordieux', '2', '0', NULL, NULL, '15cm/6cm', NULL, '2000', ""),
(NULL, 'statue-religieuse-resine-colore-jesus-misericordieux', '2', '0', NULL, NULL, '20cm/8cm', NULL, '50000', ""),
(NULL, 'statue-religieuse-resine-colore-jesus-misericordieux', '2', '0', NULL, NULL, '25m/10cm', NULL, '10000', ""),
(NULL, 'statue-religieuse-resine-lumineuse-sainte-vierge-marie-notre-dame-toute-grace', '2', '0', NULL, NULL, '10cm/4cm', NULL, '1000', ""),
(NULL, 'statue-religieuse-resine-lumineuse-sainte-vierge-marie-notre-dame-toute-grace', '2', '0', NULL, NULL, '15cm/6cm', NULL, '2000', ""),
(NULL, 'statue-religieuse-resine-lumineuse-sainte-vierge-marie-notre-dame-toute-grace', '2', '0', NULL, NULL, '20cm/8cm', NULL, '50000', ""),
(NULL, 'statue-religieuse-resine-lumineuse-sainte-vierge-marie-notre-dame-toute-grace', '2', '0', NULL, NULL, '25m/10cm', NULL, '10000', ""),
(NULL, 'statue-religieuse-resine-lumineuse-jesus-misericordieux', '2', '0', NULL, NULL, '10cm/4cm', NULL, '1000', ""),
(NULL, 'statue-religieuse-resine-lumineuse-jesus-misericordieux', '2', '0', NULL, NULL, '15cm/6cm', NULL, '2000', ""),
(NULL, 'statue-religieuse-resine-lumineuse-jesus-misericordieux', '2', '0', NULL, NULL, '20cm/8cm', NULL, '50000', ""),
(NULL, 'statue-religieuse-resine-lumineuse-jesus-misericordieux', '2', '0', NULL, NULL, '25m/10cm', NULL, '10000', "");