

CREATE TABLE IF NOT EXISTS `options_article` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `img_article` varchar(150) NOT NULL ,
  `stock` varchar(6) NOT NULL DEFAULT '10',
  `vendus` int(5) NOT NULL DEFAULT '0',
  `coloris` varchar(20),
  `couverture` int(4),
  `autre` varchar(50),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `articles` (
  `id_produits` int(11) NOT NULL AUTO_INCREMENT,
  `nom` varchar(100) NOT NULL,
  `user_name` varchar(100) NOT NULL,
  `auteur` varchar(100) NOT NULL,
  `img` varchar(150) NOT NULL,
  `fr` varchar(100) NOT NULL,
  `en` varchar(100) NOT NULL,
  `es` varchar(100) NOT NULL,
  `fr1` text NOT NULL,
  `en1` text NOT NULL,
  `es1` text NOT NULL,
  `taille` varchar(15) NOT NULL,
  `materiaux` varchar(20) NOT NULL,
  `autre` varchar(20) NOT NULL,
  `prix` int(6) NOT NULL,
  `stock` int(11) NOT NULL,
  `vendus` int(11) NOT NULL DEFAULT '0',
  `actif` tinyint(1) NOT NULL DEFAULT '1',
  `code` varchar(50) NOT NULL,
  PRIMARY KEY (`id_produits`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8,

--
-- Contenu de la table `articles`
--

INSERT INTO `articles` (`id_produits`, `nom`, `user_name`, `auteur`, `img`, `fr`, `en`, `es`, `fr1`, `en1`, `es1`, `taille`, `materiaux`, `autre`, `prix`, `stock`, `vendus`, `actif`, `code`) VALUES
('', 'divers', 'publication', '', 'pierre-noire', 'Pierre noire', '', '', 'à completer', '', '', '5cm/10cm', '', '', 2000, 10, 0, 1, ''),
('', 'bibles', 'publication', '', 'la-bible-des-peuples', 'La bible des peuples', '', '', 'à completer', '', '', '5cm/10cm', '', '', 2000, 10, 0, 1, ''),
('', 'bibles', 'publication', '', 'bible-arameen', 'La bible en Araméen', '', '', 'à completer', '', '', '5cm/10cm', '', '', 2000, 10, 0, 1, ''),
('', 'bibles', 'publication', '', 'bible-communaute-chretienne', 'La bible des communautes chretiennes', '', '', 'à completer', '', '', '5cm/10cm', '', '', 2000, 10, 0, 1, ''),
('', 'bibles', 'publication', '', 'bible-de-jerusalem', 'La bible de Jérusalem', '', '', 'à completer', '', '', '5cm/10cm', '', '', 2000, 10, 0, 1, ''),
('', 'bibles', 'publication', '', 'bible-francais-courant', 'La bible en français courant', '', '', 'à completer', '', '', '5cm/10cm', '', '', 2000, 10, 0, 1, ''),
('', 'bibles', 'publication', '', 'bible-tob', 'La bible tob', '', '', 'à completer', '', '', '5cm/10cm', '', '', 2000, 10, 0, 1, ''),
('', 'bibles', 'publication', '', 'cathechisme-eglise-catholique', "Compendium du cathechisme de l'église catholique", '', '', 'à completer', '', '', '5cm/10cm', '', '', 2000, 10, 0, 1, ''),
('', 'bibles', 'publication', '', 'cathechisme-eglise-catholique', "Compendium du cathechisme de l'église catholique", '', '', 'à completer', '', '', '5cm/10cm', '', '', 2000, 10, 0, 1, ''),
('', 'bibles', 'publication', '', 'sainte-bible', "La Sainte Bible", '', '', 'à completer', '', '', '5cm/10cm', '', '', 2000, 10, 0, 1, ''),
('', 'bibles', 'publication', '', 'sainte-bible-louis-second', "La Sainte Bible Louïs second", '', '', 'à completer', '', '', '5cm/10cm', '', '', 2000, 10, 0, 1, ''),
('', 'bibles', 'publication', '', 'veillez-et-priez', "Veillez et priez", '', '', 'à completer', '', '', '5cm/10cm', '', '', 2000, 10, 0, 1, ''),
('', 'encens', 'publication', '', 'saint-jean-geranium', "Saint Jean au <b>Geranium</b>", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'encens', 'publication', '', 'saint-expedito-jasmin', "Encens Saint Expedito au <b>Jasmin</b>", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'encens', 'publication', '', 'sainte-therese-jesus-fleur-oranger', "Sainte thérèse de Jésus à la <b>Fleur d'oranger</b>", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'encens', 'publication', '', 'saint-pedro-jacinthe', "Saint Pédro à la <b>Jacinthe</b>", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'encens', 'publication', '', 'sainte-rita-mugue', "Saint Rita au <b>Muguet</b>", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'encens', 'publication', '', 'saint-francois-assise-eucalyptus', "Saint François d'Assise à <b>l'Eucalyptus</b>", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'encens', 'publication', '', 'marie-auxiliadora-jasmin', "Maria Auxiliadora au <b>Jasmin</b>", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'encens', 'publication', '', 'saint-raphael-archange-myrrhe', "Saint Raphaël archange à la <b>Myrrhe</b>", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'encens', 'publication', '', 'saint-michel-archange-encens-naturel', "Saint Michel archange à <b>l'Encens Naturel</b>", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'encens', 'publication', '', 'saint-gabriel-archange-oeillet', "Saint gabriel archange à <b>l'Oeillet</b>", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'encens', 'publication', '', 'ange-guerison-lavande', "L'ange de la guérison à la <b>Lavande</b>", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'encens', 'publication', '', 'sainte-mere-lourdes-muguet', "Sainte mère de Lourdes au <b>Muguet</b>", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'encens', 'publication', '', 'sainte-mere-du-perpetuel-secours-citron', "Sainte mère du pertpétuel secours au <b>Citron</b>", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'encens', 'publication', '', 'sainte-mere-de-fatima-rose', "Sainte mère de Fatima à la <b>Rose</b>", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'encens', 'publication', '', 'encens-jerusalem', "Encens-Jérusalem", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'encens', 'publication', '', 'encens-pontfical', "Encens-Pontifical", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'encens', 'publication', '', 'encens-st-michel', "Encens Saint-Michel", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'croix', 'publication', '', 'crucifix-bois', "Crucifix en bois", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'croix', 'publication', '', 'crucifix-bronze', "Crucifix en bronze", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'croix', 'publication', '', 'croix-posee-st-benoit-bleu', "Croix-posée de Saint Benoit", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'croix', 'publication', '', 'croix-posee-st-benoit-rouge', "Croix-posée de Saint Benoit", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'croix', 'publication', '', 'croix-eucharistie', "Croix de l'Eucharistie", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'croix', 'publication', '', 'st-benoit-beige', "Croix de Saint Benoit", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'croix', 'publication', '', 'st-benoit-marron', "Croix de Saint Benoit", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'croix', 'publication', '', 'st-benoit-doree', "Croix de Saint Benoit", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'croix', 'publication', '', 'st-benoit-petit-beige', "Croix de Saint Benoit", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'croix', 'publication', '', 'st-benoit-petit-doree', "Croix de Saint Benoit", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'croix', 'publication', '', 'st-benoit-petit-noire', "Croix de Saint Benoit", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'croix', 'publication', '', 'st-benoit-petit-verte', "Croix de Saint Benoit", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'croix', 'publication', '', 'st-benoit-bois', "Croix de Saint Benoit", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'chapelet', 'publication', '', 'chapelet-saint-esprit', "Chapelet du Saint-Esprit", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'chapelet', 'publication', '', 'chapelet-doree-1', "Chapelet dorée", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),
('', 'chapelet', 'publication', '', 'chapelet-doree-2', "Chapelet dorée", '', '', 'à completer', '', '', '', '', '', 2000, 10, 0, 1, ''),